list: $/codeclutch/outfit/models/post/columns.yaml
modelClass: Codeclutch\Outfit\Models\Post
title: Posts
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'codeclutch/outfit/posts/update/:id'
