list: $/codeclutch/outfit/models/page/columns.yaml
modelClass: Codeclutch\Outfit\Models\Page
title: Pages
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'codeclutch/outfit/pages/update/:id'
